import Foundation

enum StringCatalogSourceReferences {
    static let all: [String] = [
        String(localized: "auth.error.invalidCredentials", bundle: .module),
        String(localized: "auth.error.invalidEmailFormat", bundle: .module),
        String(localized: "auth.error.network", bundle: .module),
        String(localized: "auth.error.sessionExpired", bundle: .module),
        String(localized: "auth.error.unexpected", bundle: .module),
        String(localized: "auth.login.cta", bundle: .module),
        String(localized: "auth.login.cta.accessibility", bundle: .module),
        String(localized: "auth.login.email", bundle: .module),
        String(localized: "auth.login.email.accessibility", bundle: .module),
        String(localized: "auth.login.navigationTitle", bundle: .module),
        String(localized: "auth.login.password", bundle: .module),
        String(localized: "auth.login.password.accessibility", bundle: .module),
        String(localized: "auth.login.productName", bundle: .module),
        String(localized: "auth.login.quickAccess", bundle: .module),
        String(localized: "auth.login.quickAccess.accessibility", bundle: .module),
        String(localized: "auth.login.title", bundle: .module),
        String(localized: "boardingpass.boardingDeadline", bundle: .module),
        String(localized: "boardingpass.error.load", bundle: .module),
        String(localized: "boardingpass.error.title", bundle: .module),
        String(localized: "boardingpass.gate", bundle: .module),
        String(localized: "boardingpass.loading", bundle: .module),
        String(localized: "boardingpass.navigationTitle", bundle: .module),
        String(localized: "boardingpass.qr.accessibility", bundle: .module),
        String(localized: "boardingpass.seat", bundle: .module),
        String(localized: "flights.detail.boardingPassCTA", bundle: .module),
        String(localized: "flights.detail.boardingPassCTA.accessibility", bundle: .module),
        String(localized: "flights.detail.departureTitle", bundle: .module),
        String(localized: "flights.detail.error.title", bundle: .module),
        String(localized: "flights.detail.gateTitle", bundle: .module),
        String(localized: "flights.detail.loading", bundle: .module),
        String(localized: "flights.detail.navigationTitle", bundle: .module),
        String(localized: "flights.detail.weather.summary", bundle: .module),
        String(localized: "flights.detail.weather.title", bundle: .module),
        String(localized: "flights.error.detail", bundle: .module),
        String(localized: "flights.error.load", bundle: .module),
        String(localized: "flights.list.error.title", bundle: .module),
        String(localized: "flights.list.loading", bundle: .module),
        String(localized: "flights.list.loadingMore", bundle: .module),
        String(localized: "flights.list.logout", bundle: .module),
        String(localized: "flights.list.logout.accessibility", bundle: .module),
        String(localized: "flights.list.navigationTitle", bundle: .module),
        String(localized: "flights.list.staleWarning", bundle: .module),
        String(localized: "flights.route", bundle: .module),
        String(localized: "flights.row.accessibility", bundle: .module),
        String(localized: "flights.status.boarding", bundle: .module),
        String(localized: "flights.status.cancelled", bundle: .module),
        String(localized: "flights.status.delayed", bundle: .module),
        String(localized: "flights.status.departed", bundle: .module),
        String(localized: "flights.status.onTime", bundle: .module),
        String(localized: "shared.accessibility.labelValue", bundle: .module),
    ]
}
